name: Run Crawl Script

on:
  
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 自动运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-crawl:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 使用 Python 3.9

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django requests beautifulsoup4 python-dateutil

      # 4. 设置 Django 环境变量
      - name: Set Django environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=epg.settings" >> $GITHUB_ENV

      # 5. 运行 crawl.py
      - name: Run crawl.py
        run: |
          # python crawl.py  # 如果 crawl.py 在根目录
          python crawl/crawl.py  # 如果 crawl.py 在 crawl 目录

      # 6. 上传生成的 XML 文件作为构建产物
      - name: Upload XML file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tvmao.xml
          path: tvmao.xml
